### PR TITLE
prefix original recipients in subject

### PR DESCRIPTION
**Pull request by georf**

### CODE REVIEW

**Comment by oboxodo** [comment]
@croaky any plans to merge this or any other PR adding a feature to be able to better filter the emails when there are many people testing in staging?

**Comment by croaky** [comment]
@oboxodo Thanks for the nudge. This pull request looks reasonable to me. I can do a pass on updating this repo, merging this, and cutting a release.

> or any other PR adding a feature to be able to better filter the emails when there are many people testing in staging

Would this PR meet your need? Or is there another change you're hoping for?

**Comment by oboxodo** [comment]
Thanks for the quick response, @croaky!

> Would this PR meet your need? Or is there another change you're hoping for?

The proper feature request we got from our stakeholders is to be able to turn off email interception for specific whitelisted emails, but still, add the subject prefix about the email coming from the staging environment. This is because different groups of people are interested in different types of intercepted emails as they test different parts of our system.

As a developer, I'm pushing back on whitelisting specific emails because I don't want to ever risk the possibility of emailing a real user from our non-prod environments. But I do understand the need.

I think in an ideal world, we could assign different recipient emails depending on the type of email we're sending. I think a way to do this with "little code" could be to append the mailer action to the recipient's email, or to the subject. For example, we have a `UserMailer` class with a `processing_file_result` action. So if we have `EMAIL_RECIPIENTS="staging@example.com` then the email could be sent to `staging+user_mailer+processing_file_result@example.com` and we could set proper email filtering depending on that.

In any case, I haven't put too much thought into this and I think, for now, this PR could be enough.

Thanks for asking!

**Comment by georf** [comment]
I used my fork the last 4 years without trouble in multiple projects. So your are welcome to merge this. Perhaps some code stylings are out of date ;-)

**Comment by croaky** [comment]
Hi folks, what do you think about https://github.com/croaky/recipient_interceptor/pull/20 ? Would that work for your case @oboxodo?

**Comment by oboxodo** [comment]
@croaky: Perfect!

**Comment by croaky** [comment]
The feature this PR supports has been merged via https://github.com/croaky/recipient_interceptor/pull/20. It is released in version 0.3.0 https://rubygems.org/gems/recipient_interceptor and https://github.com/croaky/recipient_interceptor/releases/tag/v0.3.0

**Pull request closed without merging**
